[package]
name = "rnet-security"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
curve25519-dalek.workspace = true
rnet-core = { version = "0.1.0", path = "../rnet-core" }
rnet-protocol = { version = "0.1.0", path = "../rnet-protocol" }
snow.workspace = true
thiserror.workspace = true
zeroize.workspace = true
