[package]
name = "rnet-game"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
fuzzing = []

[dependencies]
bytes.workspace = true
ring.workspace = true
rnet-core = { version = "0.1.0", path = "../rnet-core" }
rnet-protocol = { version = "0.1.0", path = "../rnet-protocol" }
rnet-security = { version = "0.1.0", path = "../rnet-security" }
rnet-transport = { version = "0.1.0", path = "../rnet-transport" }
